controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    left_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    right_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    left_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    right_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# Individual wheel controllers
left_front_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_front_wheel_joint

right_front_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_front_wheel_joint

left_rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint

right_rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_wheel_joint

joint_broad:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
      - left_front_wheel_joint
      - right_front_wheel_joint